// Importando o Link do Next.js
import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  console.log("montando layout");

  return (
    <html lang="en">
      <body>
        <div>
          <h1>Menu</h1>
          {/* Corrigindo o erro: Importando o Link corretamente */}
          <Link href="/novarota">Rota1</Link> <br /><br />
          <a href="/novarota">Rota 1, jeito antigo</a>
        </div>

        {children}
      </body>
    </html>
  );
}
